const data = {
  vinyls: [
    {
      _id: '1',
      title: 'Midnights',
      artist: 'Taylor Swift',
      path: 'midnights-taylor-swift-album',
      cover: '/covers/midnights.jpg',
      genre: 'Pop',
      price: 40,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: 'Republic records album',
    },
    {
      _id: '2',
      title: 'Metallica',
      artist: 'Metallica',
      path: 'metallica-album',
      cover: '/covers/metallica.jpg',
      genre: 'Metal-Rock',
      price: 30,
      countInStock: 20,
      rating: 5.0,
      numReviews: 10,
      description: 'high quality album',
    },
    {
      _id: '3',
      title: 'Thriller',
      artist: 'Michael Jackson',
      path: 'thriller-mj-album',
      cover: '/covers/thriller.jpg',
      genre: 'Pop',
      price: 35,
      countInStock: 15,
      rating: 5.0,
      numReviews: 14,
      description: 'This album contains previously unreleased material',
    },
    {
      _id: '4',
      title: 'Innuendo',
      artist: 'Queen',
      path: 'innuendo-queen-album',
      cover: '/covers/innuendo.jpg',
      genre: 'Rock',
      price: 33,
      countInStock: 5,
      rating: 4.5,
      numReviews: 10,
      description: 'Holliwood Records Limited Edition',
    },
  ],
};

export default data;
